import createFetchClient, {
    createFinalURL,
    createQuerySerializer,
    defaultPathSerializer,
    type ParamsOption,
} from 'openapi-fetch';
import createClient from 'openapi-react-query';
import { RequiredKeysOf } from 'openapi-typescript-helpers';

import type { paths } from './openapi-spec'; // generated by openapi-typescript

// Union all parameters from all methods for a path
type AllMethodParams<T> = T extends Record<string, any> ? (T[keyof T] extends { parameters: infer P } ? P : {}) : {};

// Create a params option that includes all possible parameters
type AllParamsOption<T> =
    AllMethodParams<T> extends never
        ? { params?: {} }
        : RequiredKeysOf<AllMethodParams<T>> extends never
          ? { params?: AllMethodParams<T> }
          : { params: AllMethodParams<T> };

export const API_BASE_URL = '/';

// Get the first available method's parameters (since you don't care about the method)
type FirstMethod<T> = T extends Record<string, any> ? T[keyof T] : never;

//export function getClient<Paths extends paths>({ baseUrl }: { baseUrl: string }) {
//const fetchClient = createFetchClient<Paths>({ baseUrl });

// return {
//     ...fetchClient,
//     PATH<Path extends keyof Paths>(
//         path: Path,

const defaultQuerySerializer = createQuerySerializer();

export function getClient<Paths extends paths>({ baseUrl }: { baseUrl: string }) {
    const fetchClient = createFetchClient<Paths>({ baseUrl });

    return {
        ...fetchClient,
        PATH<Path extends keyof Paths>(
            path: Path,
            ...args: RequiredKeysOf<ParamsOption<FirstMethod<Paths[Path]>>> extends never
                ? [options?: ParamsOption<FirstMethod<Paths[Path]>>]
                : [options: ParamsOption<FirstMethod<Paths[Path]>>]
        ): string {
            if (typeof path !== 'string') {
                throw new Error('Path must be a string');
            }

            const options = args[0];

            return createFinalURL(path, {
                baseUrl,
                params: options?.params || {},
                querySerializer: defaultQuerySerializer,
            });
        },
    };
}

export const fetchClient = getClient({ baseUrl: API_BASE_URL });

fetchClient.PATH('/api/projects/{project_id}/images/{media_id}/full', {
    params: {
        path: {
            project_id: 'yyy',
            media_id: 'xxx',
        },
    },
});

fetchClient.PATH('/api/projects/{project_id}/images/{media_id}/full', {
    params: { path: { media_id, project_id } },
});

export const $api = createClient(fetchClient);
