import createFetchClient, { defaultPathSerializer, type ParamsOption } from 'openapi-fetch';
import createClient from 'openapi-react-query';
import { RequiredKeysOf } from 'openapi-typescript-helpers';

import type { paths } from './openapi-spec'; // generated by openapi-typescript

export const API_BASE_URL = '/';

// Get the first available method's parameters (since you don't care about the method)
type FirstMethod<T> = T extends Record<string, any> ? T[keyof T] : never;

export function getClient<Paths extends paths>({ baseUrl }: { baseUrl: string }) {
    const fetchClient = createFetchClient<Paths>({ baseUrl });

    return {
        ...fetchClient,
        PATH<Path extends keyof Paths>(
            path: Path,
            ...args: RequiredKeysOf<ParamsOption<FirstMethod<Paths[Path]>>> extends never
                ? [options?: ParamsOption<FirstMethod<Paths[Path]>>]
                : [options: ParamsOption<FirstMethod<Paths[Path]>>]
        ): string {
            if (typeof path !== 'string') {
                throw new Error('Path must be a string');
            }

            const options = args[0];
            let finalPath = path;

            if (options?.params?.path) {
                finalPath = defaultPathSerializer(finalPath, options.params.path);
            }

            let url = `${baseUrl}${finalPath}`;
            if (options?.params?.query) {
                const queryString = new URLSearchParams(
                    Object.entries(options.params.query)
                        .filter(([, value]) => value !== undefined && value !== null)
                        .map(([key, value]) => [key, String(value)])
                ).toString();
                if (queryString) {
                    url += `?${queryString}`;
                }
            }

            return url;
        },
    };
}

export const fetchClient = getClient({ baseUrl: API_BASE_URL });

fetchClient.PATH('/api/projects/{project_id}/images/{media_id}/full', {
    params: {
        path: {
            project_id: 'yyy',
            media_id: 'xxx',
        },
    },
});

export const $api = createClient(fetchClient);
